version: "4.1"

services:
  backend:
    build:
      context: ./backend          # was "." when compose lived in backend
      dockerfile: Dockerfile.dev
    container_name: freshcart-backend
    restart: unless-stopped
    ports:
      - "5050:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
      - postgres
    volumes:
      - ./backend:/app            # mount backend source into container
      - /app/node_modules

  mongo:
    image: mongo:6.0
    container_name: freshcart-mongo
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  postgres:
    image: postgres:15
    container_name: freshcart-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  #frontend container for Angular app
  frontend:
    build:
      context: ./frontend-start
      dockerfile: Dockerfile.dev       # dev image (ng serve)
    container_name: freshcart-frontend
    restart: unless-stopped
    ports:
      - "4300:4300"                    # browser â†’ http://localhost:4300
    depends_on:
      - backend
    volumes:
      - ./frontend-start:/app          # live code updates
      - /app/node_modules

volumes:
  mongo_data:
  postgres_data: